version: '3.8'

services:
  api:
    build: .
    container_name: express-api-mongodb
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongo 
    networks:
      - app-network

  mongo:
    image: mongo:latest 
    container_name: mongodb-container
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: